/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_mono_box444_Instrumentation */

#ifndef _Included_com_example_mono_box444_Instrumentation
#define _Included_com_example_mono_box444_Instrumentation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_mono_box444_Instrumentation
 * Method:    whoamI
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_mono_box444_Instrumentation_whoamI
  (JNIEnv *, jobject);

/*
 * Class:     com_example_mono_box444_Instrumentation
 * Method:    stub
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_mono_box444_Instrumentation_stub
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
